on:
  workflow_run:
    workflows: [checkout]
    types:
      - completed
jobs:   
  remove_packages:
    name: remove packages main
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Remove_Packages
    - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: git checkout HEAD^
    - run: echo "ğŸ This job's status is ${{ job.status }}."
      
