on:
  workflow_run:
    workflows: [checkout]
    types:
      - completed
    remove_packages:
    name: remove packages main
    runs-on: ubuntu-latest
    environment: production
        steps:
      - name: run_remove_packages_script
    - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: echo "ğŸ This job's status is ${{ job.status }}."
      
